#################### PREAMBLE
from snakemake.utils import min_version
min_version("6.0")


#################### CONFIG
configfile: "configs/snakemake/simu/ngs/snake_config.yaml"


#################### INCLUDES
include: "../../include/simu-ngs.smk"


#################### PARAMS
HEAD_DIR     = config["HEAD_DIR"]
NGS_NB_FRAGS = config["NGS_NB_FRAGS"]
SAMPLES      = config["SAMPLES"]


#################### RULES
rule all:
    input:
        simulated_read              = expand(config["HEAD_DIR"] + "/data/simulated_hap{s}/simulated.ngs.{r}.fastq", s=SAMPLES, r=["R1", "R2"])
