#################### PREAMBLE
from snakemake.utils import min_version
min_version("6.0")


#################### CONFIG
configfile: "configs/snake_config_haplotype.yaml"


#################### INCLUDES
include: "../include/vcf-norm-truth.smk"


#################### PARAMS
HEAD_DIR = config["HEAD_DIR"]
REF      = config["REF"]
SAMPLES  = config["SAMPLES"]


#################### RULES
rule all:
    input:
        simulated_haplotypes        = expand(config["HEAD_DIR"] + "/data/simulated_hap{s}/simulated.fasta", s=SAMPLES),
        simulated_variants          = expand(config["HEAD_DIR"] + "/data/simulated_hap{s}/simulated.vcf"  , s=SAMPLES),
        simulated_norm_variants     = expand(config["HEAD_DIR"] + "/data/simulated_hap{s}/simulated.normalized.sorted.vcf.gz"     , s=SAMPLES),
        simulated_norm_variants_idx = expand(config["HEAD_DIR"] + "/data/simulated_hap{s}/simulated.normalized.sorted.vcf.gz.tbi" , s=SAMPLES)


rule hap_simulator:
    input:
        ref   = config["REF"]
    output:
        fasta = config["HEAD_DIR"] + "/data/simulated_hap{sample}/simulated.fasta",
        vcf   = config["HEAD_DIR"] + "/data/simulated_hap{sample}/simulated.vcf",
    conda:
        config["HEAD_DIR"] + "/env/conda_mason.yaml"
    log:
        config["HEAD_DIR"] + "/logs/mason/mason_variator.hap{sample}.log"
    shell:
        """
            mason_variator \
                --in-reference {input.ref} \
                --out-fasta {output.fasta} \
                --out-vcf {output.vcf} \
                --seed {wildcards.sample} \
                --snp-rate 0.01 \
                --small-indel-rate 0.005 \
                --min-small-indel-size 1 \
                --max-small-indel-size 20 \
                --sv-indel-rate 0 \
                --sv-inversion-rate 0 \
                --sv-translocation-rate 0 \
                --sv-duplication-rate 0 \
                2> {log}
        """